# Generated by Django 3.2.4 on 2021-07-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_opsdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('cost_of_ops', models.IntegerField()),
                ('opsdone', models.ManyToManyField(to='core.OpsDone')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
