# Generated by Django 3.2.4 on 2021-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=255, verbose_name='نژاد'),
        ),
    ]
