# Generated by Django 3.2.4 on 2021-07-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animal_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsdone',
            name='co_ops',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسامی کمک کنندگان'),
        ),
        migrations.AddField(
            model_name='opsdone',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
        migrations.AddField(
            model_name='opsdone',
            name='main_agent',
            field=models.CharField(default='ایلفا', max_length=255, verbose_name='نام مسئول'),
        ),
        migrations.AddField(
            model_name='opsdone',
            name='support',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام حامی'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Age',
            field=models.CharField(max_length=255, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=255, verbose_name='نژاد'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cost_of_ops',
            field=models.IntegerField(verbose_name='کل هزینه ها'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('bird', 'پرنده'), ('cat', 'گربه'), ('dog', 'سگ'), ('other', 'دیگر')], default='dog', max_length=255, verbose_name='گونه'),
        ),
        migrations.AlterField(
            model_name='opsdone',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='نام عملیات'),
        ),
    ]
