# Generated by Django 3.2.4 on 2021-07-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210704_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='opsdone',
        ),
        migrations.AddField(
            model_name='animal',
            name='work_group',
            field=models.ManyToManyField(blank=True, to='core.OpsDone', verbose_name='کارگروه'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag', verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='opsdone',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام کارگروه'),
        ),
    ]
