# Generated by Django 3.2.4 on 2021-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(default='', max_length=255, verbose_name='جنسیت'),
        ),
    ]
