# Generated by Django 3.2.4 on 2021-07-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='work_group',
            field=models.ManyToManyField(blank=True, to='core.OpsDone'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='تگ'),
        ),
    ]
