# Generated by Django 3.2.4 on 2021-07-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210705_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opsdone',
            options={'verbose_name': 'کارگروه', 'verbose_name_plural': 'کارگروه'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='تگ', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='work_group',
            field=models.ManyToManyField(blank=True, related_name='کارگروه', to='core.OpsDone'),
        ),
    ]
