# Generated by Django 3.2.4 on 2021-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210706_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsdone',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
