# Generated by Django 3.2.4 on 2021-07-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210706_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag', verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='work_group',
            field=models.ManyToManyField(blank=True, to='core.OpsDone', verbose_name='کارگروه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
    ]
