# Generated by Django 3.2.4 on 2021-07-06 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210706_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'حیوان', 'verbose_name_plural': 'حیوانات'},
        ),
        migrations.AlterModelOptions(
            name='opsdone',
            options={'verbose_name': 'کارگروه', 'verbose_name_plural': 'کارگروه ها'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='opsdone',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام کارگروه'),
        ),
        migrations.AlterField(
            model_name='opsdone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
