# Generated by Django 3.2.4 on 2021-07-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210706_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpsDone',
            new_name='WorkGroup',
        ),
    ]
