# Generated by Django 3.2.4 on 2021-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_opsdone_workgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(default='dog', max_length=255, verbose_name='گونه'),
        ),
    ]
